spring:
  datasource:
    url: jdbc:mysql://10.201.186.249:3306/media_database?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
#  freemarker:
#    suffix: .html,.jpg,.png,.gif
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.myself.mybatis.entity


devtools:
  remote:
    restart:
      enabled: true
      additional-paths: src/main/java

jpa:
  show-sql: true
  hibernate:
    ddl-auto:update
server:
  port: 8080
  max-http-header-size: 1MB




